[book]
authors = ["Ben Pfaff"]
language = "en"
multilingual = false
src = "src"
title = "GNU PSPP"

[output.html]
mathjax-support = true

[output.linkcheck]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
