[package]
name = "pspp-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for building PSPP"
license = "GPL-3.0-or-later"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[lib]
proc-macro = true
